### ISSUE TITLE
Chapter 4: compile errors

### ISSUE THREAD

**Issue by axedre** [openglbook/openglbook-samples#1]
I'm having trouble compiling chapter 4 (I use the OpenGL 3.3 compatibility version and have left the sample code untouched).

```
$ glcc chapter.4.1.c 

/tmp/ccdKKCwm.o: In function `Initialize':
chapter.4.1.c:(.text+0xee): undefined reference to `ExitOnGLError'
chapter.4.1.c:(.text+0x116): undefined reference to `ExitOnGLError'
chapter.4.1.c:(.text+0x11d): undefined reference to `IDENTITY_MATRIX'
chapter.4.1.c:(.text+0x12b): undefined reference to `IDENTITY_MATRIX'
chapter.4.1.c:(.text+0x139): undefined reference to `IDENTITY_MATRIX'
chapter.4.1.c:(.text+0x147): undefined reference to `IDENTITY_MATRIX'
chapter.4.1.c:(.text+0x155): undefined reference to `IDENTITY_MATRIX'
/tmp/ccdKKCwm.o:chapter.4.1.c:(.text+0x163): more undefined references to `IDENTITY_MATRIX' follow
/tmp/ccdKKCwm.o: In function `Initialize':
chapter.4.1.c:(.text+0x280): undefined reference to `TranslateMatrix'
/tmp/ccdKKCwm.o: In function `ResizeFunction':
chapter.4.1.c:(.text+0x400): undefined reference to `CreateProjectionMatrix'
/tmp/ccdKKCwm.o: In function `CreateCube':
chapter.4.1.c:(.text+0x5b8): undefined reference to `ExitOnGLError'
chapter.4.1.c:(.text+0x5c7): undefined reference to `LoadShader'
chapter.4.1.c:(.text+0x5dc): undefined reference to `LoadShader'
chapter.4.1.c:(.text+0x62f): undefined reference to `ExitOnGLError'
chapter.4.1.c:(.text+0x68d): undefined reference to `ExitOnGLError'
chapter.4.1.c:(.text+0x6aa): undefined reference to `ExitOnGLError'
chapter.4.1.c:(.text+0x6c5): undefined reference to `ExitOnGLError'
chapter.4.1.c:(.text+0x6eb): undefined reference to `ExitOnGLError'
/tmp/ccdKKCwm.o:chapter.4.1.c:(.text+0x708): more undefined references to `ExitOnGLError' follow
/tmp/ccdKKCwm.o: In function `DrawCube':
chapter.4.1.c:(.text+0x91a): undefined reference to `DegreesToRadians'
chapter.4.1.c:(.text+0x933): undefined reference to `IDENTITY_MATRIX'
chapter.4.1.c:(.text+0x941): undefined reference to `IDENTITY_MATRIX'
chapter.4.1.c:(.text+0x94f): undefined reference to `IDENTITY_MATRIX'
chapter.4.1.c:(.text+0x95d): undefined reference to `IDENTITY_MATRIX'
chapter.4.1.c:(.text+0x96b): undefined reference to `IDENTITY_MATRIX'
/tmp/ccdKKCwm.o:chapter.4.1.c:(.text+0x979): more undefined references to `IDENTITY_MATRIX' follow
/tmp/ccdKKCwm.o: In function `DrawCube':
chapter.4.1.c:(.text+0x9b1): undefined reference to `RotateAboutY'
chapter.4.1.c:(.text+0x9c6): undefined reference to `RotateAboutX'
chapter.4.1.c:(.text+0x9e1): undefined reference to `ExitOnGLError'
chapter.4.1.c:(.text+0xa2b): undefined reference to `ExitOnGLError'
chapter.4.1.c:(.text+0xa46): undefined reference to `ExitOnGLError'
chapter.4.1.c:(.text+0xa69): undefined reference to `ExitOnGLError'
collect2: error: ld returned 1 exit status
```

Where glcc is an alias I've defined as:

```
alias glcc='clear; gcc -lGL -lGLU -lGLEW -lglut'
```

I basically stuffed all the OpenGL-related libraries I could think of in the linker, but I'm not sure they are all necessary; still, it doesn't seem that removing one or more linked libraries gets me any where closer to compilation, in fact it spews out even more errors.
Could you shed some light on which libraries need to be linked and what they stand for?
Also, any idea why it's not compiling?
Thanks in advance.

**Comment by EddyLuten** [comment]
You need to include `Utils.c` in your build as described in the text. Let me know if you are still unable to build it after this.

**Comment by axedre** [comment]
Ah, silly me! But then again, I searched the page for Chapter 4 for occurrences of "Utils.c" and it never explicitly says the file is to be included. Can you indicate where I can find this instruction?
Could it possibily be a typeo in the source code? For I see both `chapter.4.1.c` and `Utils.c` include `Utils.h`, but shouldn't the latter be the one including `Utils.h` and the former include `Utils.c`?
Anyhow, having tried replacing `Utils.h` with `Utils.c` in `chapter.4.1.c` still yields some compilations errors:

```
In file included from chapter.4.1.c:1:0:
../Utils.c: In function ‘ScaleMatrix’:
../Utils.c:49:3: error: invalid use of non-lvalue array
   memcpy(m->m, MultiplyMatrices(m, &scale).m, sizeof(m->m));
   ^
../Utils.c: In function ‘TranslateMatrix’:
../Utils.c:60:3: error: invalid use of non-lvalue array
   memcpy(m->m, MultiplyMatrices(m, &translation).m, sizeof(m->m));
   ^
../Utils.c: In function ‘RotateAboutX’:
../Utils.c:74:3: error: invalid use of non-lvalue array
   memcpy(m->m, MultiplyMatrices(m, &rotation).m, sizeof(m->m));
   ^
../Utils.c: In function ‘RotateAboutY’:
../Utils.c:88:3: error: invalid use of non-lvalue array
   memcpy(m->m, MultiplyMatrices(m, &rotation).m, sizeof(m->m));
   ^
../Utils.c: In function ‘RotateAboutZ’:
../Utils.c:102:3: error: invalid use of non-lvalue array
   memcpy(m->m, MultiplyMatrices(m, &rotation).m, sizeof(m->m));
```

Finally, do you confirm that all the libraries I link at compile time (`gcc -lGL -lGLU -lGLEW -lglut`) are actually necessary?
Thanks.

_EDIT:_ it appears someone else has stumped into this: http://stackoverflow.com/questions/6645624/c-invalid-use-of-non-lvalue-array, I will try to see if I can apply one of the given solutions and get back to you.

**Comment by axedre** [comment]
After fiddling around with the code (kinda rusty with C) I surrendered to the OP's own solution: declaring a temporary variable: `Matrix tmp = MultiplyMatrices(m, ...); memcpy(m->m, tmp.m, sizeof(m->m));`.
Cheers.

**Comment by EddyLuten** [comment]
Hi @axedre, I'm glad you've figured it out. I'm filing a separate bug for the `MultiplyMatrices` issue with GCC. As for the libraries, I'm positive you can compile it without GLU support.

As for the explicit statement to include `Utils.c` in your compilation, I'm pretty sure that since half of chapter 4 is dedicated what's in the helper library and the first statement is:

> We use many of the functions from this chapter in the rest of the book, so let's create a few files that we can carry over from chapter to chapter.

I think it's kind of implied that it should be included in the compilation of your program (also considering `Utils.h` is included in the chapter 4 source files). Also, beware that none of the code is tested with GLUT, only with FreeGLUT, I can't vouch for the results you're going to get.

Let me know if you run into any more issues along the way, especially with GCC since most of the development of the code was initially done using MSVC.

Thanks! :thumbsup:

**Comment by axedre** [comment]
Thank _you_! :)
There are in fact a couple more things that I should like to report:
1. In chapter.4.1.c, these instructions

``` C
ShaderIds[1] = LoadShader("./OpenGL 3.3/SimpleShader.fragment.3.3.glsl", GL_FRAGMENT_SHADER);
ShaderIds[2] = LoadShader("./OpenGL 3.3/SimpleShader.vertex.3.3.glsl", GL_VERTEX_SHADER);
```

(lines 207 & 208) cause failure at run-time since the path to those files is wrong. Fixed it by removing the `OpenGL 3.3/` part of the path.
2. I noticed on the tutorial page for chapter 4 that the screenshots report a frame rate of ~2644 fps, while on my machine it never goes over 60 fps. Excuse my ignorance if this strikes as a naïve question, but why does this occur? And what could I do to improve the frame rate? The cube spins excruciatingly slow.

Thanks for the impeccable support.

**Comment by EddyLuten** [comment]
Thanks, created a new bug for that issue.

As for FPS, see the section named "Vertical Sync" in chapter 1, which will explain why your framerate seems to be low (it's not).

Also, to increase the rate at which the cube spins (this is not related to your FPS), you can increase the hardcoded "45.0f" value with a higher rate. This basically says, rotate the cube at 45 degrees per second. Try replacing it with 90 or 180 and see what happens.

**Comment by axedre** [comment]
Hi Eddy,
sorry I couldn't get back to you sooner.
As far as compiling goes, removing GLU support (i.e.: compiling with `gcc -lGL -lGLEW -lglut -lm chapter.4.1.c`) yields the following error:

```
/tmp/ccgYyqhn.o: In function `ExitOnGLError':
chapter.4.1.c:(.text+0x961): undefined reference to `gluErrorString'
collect2: error: ld returned 1 exit status
```

which is gone as soon as I restore `-lGLU` in my command line.
As per the frame rate, I read the section about Vertical Sync, it's all clear now, thanks.
Replacing 45 with 180 or 360 does indeed _slightly_ speed up the cube's rotation, albeit not as much as I expected  (but this might be caused by my poor old pc! :)). But what is actually a little annoying is the "jumpy" behavior the cube has, it rotates smoothly for a bit, then "skips". I have double-checked: it's not due to the screencast recording in progress for it does that even when screen capturing is off; see for yourself: [Cube @ 180](http://axedre.net/cube180.webm), [Cube @ 360](http://axedre.net/cube360.webm). Any idea what could be the reason for this behavior? (I promise I will not bother you further, I'm almost good to go :))
Cheers.

**Comment by EddyLuten** [comment]
Strange, I have no idea why it's stuttering like that. Can you tell me what kind of hardware, OS, and GPU driver version you're running it on? And thanks for the GLU verification, I forgot about that function call to `gluErrorString`.

Do any other games or OpenGL applications run smoothly for you on your OS?

**Comment by axedre** [comment]
I have an nVidia GeForce G102M GPU updated to driver version 304.123 running on ArchLinux 64-bit, 4 gigs of RAM and an Intel Core 2 Duo T6500 @ 2.10 GHz x 2. If I forgot any other valueable detail, please let me know.
I have no other experience of OpenGL applications running on my machine, is there a tool I can download to benchmark the performances? WebGLs seem to run pretty smoothly, on the other hand.
